### ISSUE TITLE
j'arrive pas à commit alors je fais un issue:D

### ISSUE THREAD

**Issue by ghost** [Altraya/S5_Projet_Reseau#2]
/\* je sais pas si je suis trop fatiguée ou quoi mais il veut pas commit le serveur de l'exo4 
donc je le passe comme ça 
bref ça craint_/
/_======================================================
            serveur.c
            Bit Alterné
./serveur <fichier_a_envoyer> <fichier_recu> <port_locale>
./serveur envoieServ.txt recuServ.txt 5000
 ======================================================*/
# include <sys/stat.h>
# include <fcntl.h>
# include <unistd.h>
# include <sys/types.h>
# include <sys/socket.h>
# include <stdio.h>
# include <stdlib.h>
# include <arpa/inet.h>
# include <string.h>
# define BUFFER_LENGTH 1024

typedef struct message_s 
{
    char buf[BUFFER_LENGTH];
    short int fin;
    int taille;
    short int bit;
}message;

message\* initMessage()
{
    message\* m = malloc(sizeof(struct message_s));
    m->fin=0;
    return m;
}

int main(int argc, char *_argv)
{
    if (argc < 4)
    {
        fprintf(stderr, "Usage: %s <fichier_a_envoyer>  <fichier_recu> <port_local>\n", argv[0]);
        exit(1);
    }
    char_ nomFichierAEnvoyer = argv[1];
    char\* nomFichierRecu = argv[2];
    printf("Nom fichier a envoye: %s\n", nomFichierAEnvoyer);
    printf("Nom fichier recu %s\n", nomFichierRecu);
    int port = atoi(argv[3]);
    printf("Port : %d\n", port);

```
int input_fd;
int output_fd;
int nbchar;

//Adresse locale
struct sockaddr_in adrLocale;
adrLocale.sin_family = AF_INET;
adrLocale.sin_addr.s_addr = htonl(INADDR_ANY);
adrLocale.sin_port = htons(port); 

int fd;
fd=socket(AF_INET,SOCK_DGRAM,0);
if(fd==-1)
{
    perror("socket");
    exit(1);
}

if(bind(fd,(struct sockaddr*)&adrLocale,sizeof(adrLocale))==-1)
{
    perror("bind");
    exit(2);
}

//Connexion : adresse du client qui nous a contacté
struct sockaddr_in adrDist;
adrDist.sin_family = AF_INET;

char buffConnexion[0];
int nbCharCon = 0;
socklen_t b = sizeof(adrDist);

printf("En attente d'une connexion \n");
nbCharCon = recvfrom(fd, buffConnexion, 0, 0, (struct sockaddr*)&adrDist, &b);
printf("Connexion en cours : Le serveur a recu un datagramme de : %d octets\n", nbCharCon);

printf("Ip adresse locale : %s\n", inet_ntoa(adrLocale.sin_addr));
printf("Port locale %d\n", ntohs(adrLocale.sin_port));


printf("Ipclient : %s \n", inet_ntoa(adrDist.sin_addr));
printf("Port client %d\n", ntohs(adrDist.sin_port));

printf("Connexion réussie \n");

// ouvrir le fichier a envoyer en lecture
input_fd = open(nomFichierAEnvoyer, O_RDONLY);
if(input_fd<0)
{   
    perror("open input"); 
    exit(1);        
}
printf("Ouverture du fichier %s\n", nomFichierAEnvoyer);

//check si le fichier existe déjà pour le delete et pas avoir une erreur => plus pratique pour les tests
// ouvrir le fichier en ecriture que l'on recoit
output_fd = open(nomFichierRecu, O_CREAT | O_WRONLY, S_IRUSR | S_IWUSR);
if(output_fd<0)
{   
    perror("open output");
    exit(1);        
}
printf("Ouverture du fichier nomFichierRecu %s\n", nomFichierRecu);

// copie :
message* messageRecu = initMessage();
message* messageAEnvoyer = initMessage();
message* msg_ack = initMessage();
int nbLuEnvoi = 0;
int nbLuRecoi = 0;
socklen_t addrDist = sizeof(adrDist);
socklen_t addrLocale = sizeof(adrLocale);
short int ack_v = 0;
while(!(messageRecu->fin && messageAEnvoyer->fin))
{
    //tant qu'il y a des messages à recevoir
    if(!messageRecu->fin)
    {
        nbLuRecoi = recvfrom(fd, messageRecu, sizeof(message), 0,(struct sockaddr*)&adrLocale, &addrLocale);
        //quand on reçoit un message on doit envoyer le ack.
        printf("Le serveur a recu %d octets \n", nbLuRecoi);
        msg_ack->bit = messageRecu->bit;
        msg_ack->ack = 1;
        msg_ack->buf = "ceci est un ack :D";
        //si jamais le ack se perd malencontreusement, le client va renvoyer le même message
        //qu'il faudra ignorer par la suite.
        sendto(fd, msg_ack, sizeof(message), 0, (struct sockaddr*)&adrDist, addrDist);
        if(messageRecu->fin)
            printf("Le serveur ferme la connexion l'émetteur (client) a envoyé une demande de fermeture\n");
        //si on a bien la trame attendue on consomme les données
        if(messageRecu->bit==ack_v)
        {
            write(output_fd, messageRecu->buf, messageRecu->taille);
        }
        //sinon, on s'en branle

        //on actualise le numéro de la prochaine trame attendue
        (ack_v+=1)%2; 
    }

    if(!messageAEnvoyer->fin)
    {
        nbLuEnvoi = read(input_fd, messageAEnvoyer->buf, BUFFER_LENGTH);
        messageAEnvoyer->taille=nbLuEnvoi;
        if(nbLuEnvoi < BUFFER_LENGTH)
        {
            messageAEnvoyer->fin=1;
            printf("Le serveur envoi une demande de fermeture de connexion \n");            
        }

        nbchar=sendto(fd, messageAEnvoyer, sizeof(message), 0, (struct sockaddr*)&adrDist, addrDist);
        printf("Le serveur envoi %d octets \n", nbchar);
    }

}
close(input_fd);
close(output_fd);
return 0;
```

}

**Comment by ghost** [comment]
Je comprend pas tout.

**Comment by Altraya** [comment]
Il manque un acquitement de la connexion non ? 
Tu peux enlever le commentaire //sinon, on s'en branle ?
Pourquoi t'arrives pas a commit ? T'es sous linux ou windows ? (Si t'es sous windows DL tortoise git ca t'aideras) Il te dit quoi git ? Sous linux faut git add avant de faire un git commit..
Est ce que tu as la partie client.c ?
T'as test avec les configs qu'on demande dans le goBackN avec le médium ?

**Comment by ghost** [comment]
je n'ai pas fait le gobackN je finis le bit alterné là

2015-12-05 19:16 GMT+01:00 Altraya notifications@github.com:

**Comment by Altraya** [comment]
Oui, je sais, mais est ce que t'as essayé le programme médium avec les x, y donnés dans le goBackN ? Genre (0,0) (0.5,0) etc.
(Et mes autres questions ? :3)

**Comment by Altraya** [comment]
Pour le goBackN il faut que ce soit en transfert unidirectionnelle ou bidirectionnelle ?

**Comment by Lukc** [comment]
A priori, en bidirectionnel. Si l’architecture du projet est décente, ça fait aucune différence de toute façon.

De plus, si le GoBackN est implémenté, la méthode des bits alternés l’est de fait (fenêtre de taille 1, tout ça).

**Comment by ghost** [comment]
tout à fait.

**Comment by ghost** [comment]
Sinon, je règle les problèmes de connexion, je suis sous windows (bouuuuh) de quel client.c parles-tu ?

**Comment by Lukc** [comment]
Celui des bits alternés, je suppose.

**Comment by Altraya** [comment]
Oui celui du bit alterné.

Ca me prend la tête j'ai des problèmes de warning qui sortent de nul part alors que j'ai bien mes fichiers d'include...

**Comment by ghost** [comment]
j'ai commit si tu veux voir mais je bloque sur un truc con, peut-être que tu va voir l'erreur...

**Comment by Altraya** [comment]
Question ils marchent tes timers ? Tu as utilisé la structure de datagramme du prof ou tu as fait un truc a toi? Parce que la j'ai une structure speciale pour nos messages, et une a part pour les acquitements, mais du coup j'arrive pas a faire ce que je veux >.<'

**Comment by ghost** [comment]
j'utilise la même structure pour les messages et les ack, je vois pas comment tu veux faire autrement... Mes timers sont supposés fonctionner...

**Comment by ghost** [comment]
Le medium il te change aussi des bits dans la structure message ? genre j'envoie un message avec le bit fin à 1 et lors du recvfrom il est à zéro... Quand j'exécute mon programme sans le medium je n'ai pas ce problème.

**Comment by Altraya** [comment]
Bah c'est pas qu'il t'enleves un paquet? Hum... je sais que d'autres gens ont eu le problème... mais je vois pas d'ou ca peut venir... a regarder de plus pret le médium ? Je fini le goBackN et j'te file un coup de patte.
